[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
ethereum-types = "0.15.1"
readb = "0.4.1"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.142"
sha2 = "0.10.9"
